daily/0519/workshop/crud/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

daily/0519/workshop/crud/articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/like_api/', views.like_api, name='like_api'),
]

daily/0519/workshop/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

daily/0519/workshop/crud/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

daily/0519/workshop/crud/articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')

daily/0519/workshop/crud/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

daily/0519/workshop/crud/articles/forms.py
from django import forms 
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ['like_users', 'user']

daily/0519/workshop/crud/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_POST
from .forms import CustomUserCreationForm


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('articles:index')

daily/0519/workshop/crud/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

@login_required
def like(request, article_pk):
    user = request.user 
    article = get_object_or_404(Article, pk=article_pk)
    
    if article.like_users.filter(pk=user.pk).exists():
        article.like_users.remove(user)
    else:
        article.like_users.add(user)

    return redirect('articles:index')

@login_required
def like_api(request, article_pk):
    user = request.user 
    article = get_object_or_404(Article, pk=article_pk)
    
    if article.like_users.filter(pk=user.pk).exists():
        article.like_users.remove(user)
        liked = False
    else:
        article.like_users.add(user)
        liked = True

    context = {
        'liked': liked,
        'count': article.like_users.count()
    }
    return JsonResponse(context)

daily/0519/workshop/crud/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>로그인</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>로그인</button>
    </form>
{% endblock %}

daily/0519/workshop/crud/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>회원가입</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>회원가입</button>
    </form>
{% endblock %}

daily/0519/workshop/crud/articles/templates/articles/form.html
{% extends 'base.html' %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>글 작성</button>
  </form>
{% endblock %}

daily/0519/workshop/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h2>INDEX</h2>
  {% for article in articles %}
    <h3>작성자: {{ article.user }}</h3>
    <h4>제목: {{ article.title }}</h4>
    <p>내용: {{ article.content }}</p>
    <!-- <span>AJAX 방식</span> -->
    {% if user in article.like_users.all %}
      <i class="fas fa-heart fa-lg like-buttons" style="color:crimson" data-id="{{ article.pk }}"></i>
    {% else %}
      <i class="fas fa-heart fa-lg like-buttons" style="color:black" data-id="{{ article.pk }}"></i>
    {% endif %}

    <!-- <span>기존 방식</span>  
    <a href="{% url 'articles:like' article.pk %}">
      {% if user in article.like_users.all %}
        <i class="fas fa-heart fa-lg" style="color:crimson"></i>
      {% else %}
        <i class="fas fa-heart fa-lg" style="color:black"></i>
      {% endif %}
    </a> -->
    <span id="like-count-{{ article.pk }}">{{ article.like_users.all|length }}</span>명이 이 글을 좋아합니다.
    <hr>
  {% endfor %}
  <a href="{% url 'articles:create' %}">CREATE</a>
  <script>
    const likeButtonList = document.querySelectorAll('.like-buttons')
    likeButtonList.forEach(likeButton => {
      likeButton.addEventListener('click', e => {
        // 1. axios로 요청보내기(like)
        // const articleID = e.target.getAttribute('data-id')
        const articleID = e.target.dataset.id // dataset => data라고 시작하는 속성들 반환
        {% if user.is_authenticated %}
        axios.get(`/articles/${articleID}/like_api/`)
          .then(res => {
            // 현재 DB에 저장된 값이 liked=True면
            if (res.data.liked) {
              e.target.style.color = 'crimson'
            } else {
              e.target.style.color = 'black'
            }
            document.querySelector(`#like-count-${articleID}`).innerText = res.data.count
          })
        {% else %}
          alert('비로그인 사용자는 좋아요를 누를 수 없습니다.')
        {% endif %}
      })
    }) 
  </script>
{% endblock %}

daily/0519/workshop/crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>workshop</title>
  <!-- font-awesome -->
  <script src="https://kit.fontawesome.com/e26b215976.js" crossorigin="anonymous"></script>
  <!-- axios -->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>
<body>
  {% if request.user.is_authenticated %}
    <li>
      {{ request.user.username }}님 로그인
    </li>
    <li>
      <a href="{% url 'accounts:logout' %}">로그아웃</a>
    </li>
  {% else %}
    <li>
      <a href="{% url 'accounts:login' %}">로그인</a>
    </li>
    <li>
      <a href="{% url 'accounts:signup' %}">회원가입</a>
    </li>
  {% endif %}

  {% block content %}
  {% endblock %}
</body>
</html>